import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';

test('guide uses current catalog and honest commercial terms', async () => {
  const html = await readFile('site/dist/index.html', 'utf8');
  const entries = JSON.parse(await readFile('templates.json', 'utf8'));
  assert.equal((html.match(/class="catalog-card"/g) || []).length, entries.length);
  assert.ok(html.includes(`${entries.length}サイト収録中`));
  assert.ok(html.includes('2,500'));
  assert.ok(html.includes('noteでのお申し込みは、準備中'));
  assert.ok(html.includes('新しい商用サイト'));
  assert.ok(!html.includes('{{'));
  assert.ok(!html.includes('2,000'));
  assert.ok(html.includes('<h2>FAQ</h2>'));
  assert.ok(html.includes('日本語LP<br>テンプレート集'));
  assert.ok(html.includes('収録テンプレート一覧はこちら'));
  assert.ok(!html.includes('目標は、業種別の約10サイト'));
  assert.ok(!html.includes('ジムLPは編集用ソースの確認後'));
  assert.equal(entries.at(-1).id, 'ikeoji-live');
  assert.equal(entries.at(-2).id, 'move-fit-gym');
  assert.equal(entries.at(-3).id, 'home-care-template');
  assert.equal(entries.at(-4).id, 'clinic-template');
  assert.ok(html.includes('https://home-care-template-psi.vercel.app/'));
  assert.ok(html.includes('あすの訪問介護'));
  assert.ok(html.includes('https://clinic-template-hazel.vercel.app/'));
  assert.ok(html.includes('そら内科クリニック'));
  assert.ok(html.includes('https://daikanyama.vercel.app/'));
  assert.ok(html.includes('https://move-fit-gym-pi.vercel.app/'));
  assert.ok(!html.includes('つくる、その先へ'));
  assert.ok(html.includes('商用で使えますか？'));
  assert.ok(!html.includes('今、10サイトすべて使えますか'));
  assert.ok(!html.includes('BUILT TOGETHER'));
  assert.ok(!html.includes('Pull Requestから参加'));
  for (const match of html.matchAll(/(?:src|href)="(\/[^"#]*)"/g)) await access(`site/dist${match[1]}`);
  const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(m => m[1]));
  for (const match of html.matchAll(/href="#([^"]+)"/g)) assert.ok(ids.has(match[1]), `Broken anchor: ${match[1]}`);
});
