import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, CalendarBlank, CheckCircle, Clock, Heart, Leaf, MapPin, List, Phone, Plus, Sparkle, User, X} from '@phosphor-icons/react';
import './styles.css';

const nav=[['ホーム','home'],['当院の特徴','about'],['施術メニュー','menu'],['お客様の声','voices'],['院長紹介','doctor'],['アクセス','access'],['よくある質問','faq']];
const menuItems=[['整体コース','60分','6,000円','全身のバランスを整え、不調の根本から改善します。'],['骨盤矯正コース','60分','6,500円','骨盤の歪みを整え、姿勢・身体のクセを改善します。'],['マタニティ整体','60分','6,000円','妊娠中の不調に配慮したやさしい施術です。']];
const faqs=[['初めてでも大丈夫ですか？','はい。カウンセリングでお悩みや生活習慣を丁寧に伺い、お一人おひとりに合わせてご案内します。'],['どのくらいの頻度で通えば良いですか？','お身体の状態や目標によって異なります。施術後に無理のないペースをご提案します。'],['着替えはありますか？','動きやすいお着替えをご用意しています。手ぶらでお越しいただけます。'],['保険は使えますか？','当院は自費施術です。料金はメニュー欄をご確認ください。'],['駐車場はありますか？','近隣コインパーキングをご利用ください。駅から徒歩3分の場所にあります。']];
function Button({children='今すぐ予約する',onClick}){return <button className="button" onClick={onClick}>{children}<ArrowRight weight="bold"/></button>}
function Booking({onClose}){const [sent,setSent]=useState(false);return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="modal-close" onClick={onClose} aria-label="閉じる"><X/></button>{sent?<><CheckCircle size={42} weight="thin" className="success-icon"/><h2 id="booking-title">確認できました</h2><p>これはテンプレートの入力デモです。送信・予約確定は行われません。</p><Button onClick={onClose}>閉じる</Button></>:<><p className="eyebrow">RESERVATION / DEMO</p><h2 id="booking-title">初回体験を予約する</h2><p className="notice">入力・確認だけのデモです。実際の予約は送信されません。</p><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>希望メニュー<select required><option>整体コース（60分）</option><option>骨盤矯正コース（60分）</option><option>マタニティ整体（60分）</option></select></label><label>希望日<input type="date" required/></label><label>お名前<input required placeholder="例）山田 花子"/></label><label>メールアドレス<input type="email" required placeholder="例）info@example.com"/></label><label className="check"><input type="checkbox" required/> 予約が送信されないデモであることを確認しました。</label><button className="button" type="submit">入力内容を確認する <ArrowRight weight="bold"/></button></form></>}</div></div>}
function App(){const [menu,setMenu]=useState(false),[booking,setBooking]=useState(false);return <div className="site" id="home"><a className="skip" href="#main">本文へ移動</a><header className="header"><a className="brand" href="#home"><Leaf size={31} weight="thin"/><span>やすらぎ整体院<small>YASURAGI SEITAIIN</small></span></a><nav className={menu?'nav open':'nav'}>{nav.map(([text,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{text}</a>)}</nav><Button onClick={()=>setBooking(true)}>ご予約・お問い合わせ</Button><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'メニューを閉じる':'メニューを開く'}>{menu?<X/>:<List/>}</button></header>
<main id="main"><section className="hero"><img src="/assets/hero.png" alt="施術を受ける女性と整体師"/><div className="hero-copy"><p className="eyebrow">YASURAGI SEITAIIN</p><h1>からだが変わると、<br/>毎日がもっと<br/><em>軽やか</em>になる。</h1><p>肩こり・腰痛・姿勢の改善を通して、<br/>あなたの「なりたい身体」を<br/>サポートします。</p><Button onClick={()=>setBooking(true)}>今すぐ予約する</Button></div><p className="hero-script">A Lighter<br/>Tomorrow</p><div className="price-badge"><small>初めての方</small><strong>初回体験</strong><b>3,980<small>円</small></b><span>（通常 6,000円）</span></div></section>
<section className="feature-strip">{[[User,'肩こり・首こりの攻略'],[Sparkle,'腰痛・坐骨神経痛の緩和'],[Leaf,'姿勢・骨盤の調整'],[Heart,'スポーツのパフォーマンス向上'],[CheckCircle,'心と身体のリフレッシュ']].map(([I,t])=><div key={t}><I size={34} weight="thin"/><span>{t}</span></div>)}</section>
<section className="section about" id="about"><div className="room-photo"><img src="/assets/consultation.png" alt="明るい整体院でのカウンセリング"/><span>整えて、<br/>もっと自分らしく。</span></div><div><p className="eyebrow">ABOUT / お悩み</p><h2>このようなお悩みは<br/>ありませんか？</h2><ul className="checks">{['デスクワークで肩や首がつらい','慢性的な腰痛で日常生活がつらい','姿勢の悪さや猫背が気になる','疲れが抜けにくく、体が重い','どこに行っても良くならなかった'].map(t=><li key={t}><CheckCircle weight="fill"/>{t}</li>)}</ul></div></section>
<section className="section flow"><p className="eyebrow">FLOW / 施術の流れ</p><h2>あなたの身体に合わせた、<br/>オーダーメイド施術。</h2><div className="flow-grid">{[['01','カウンセリング','お悩みや生活習慣を丁寧にお伺いします。'],['02','検査・姿勢チェック','姿勢や可動域を確認し、原因を見つけます。'],['03','施術','一人ひとりに合わせた施術を行います。'],['04','アフターケア','セルフケアのアドバイスをお伝えします。']].map(([n,t,d],i)=><article key={n}><div className="flow-image"><img src={i===2?'/assets/treatment.png':'/assets/consultation.png'} alt=""/></div><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section menu-section" id="menu"><div className="section-heading"><div><p className="eyebrow">MENU / 施術メニュー</p><h2>身体の状態に合わせた<br/>3つのコース。</h2></div><a href="#contact">すべてのメニューを見る <ArrowRight/></a></div><div className="menu-grid">{menuItems.map(([t,time,price,d])=><article key={t}><span>{time}</span><h3>{t}</h3><strong>{price}</strong><p>{d}</p></article>)}</div><div className="first-visit"><span>初めての方限定</span><b>初回体験 <strong>3,980円</strong></b><Button onClick={()=>setBooking(true)}>体験を予約する</Button></div></section>
<section className="reasons"><div><p className="eyebrow">WHY US / 選ばれる5つの理由</p><h2>安心して通える<br/>整体院であるために。</h2></div><ol>{['国家資格保有者による安心の施術','一人ひとりに合わせたオーダーメイド施術','再発しにくい身体づくりのサポート','駅から徒歩3分・通いやすい立地','清潔で落ち着いた空間・完全予約制'].map((t,i)=><li key={t}><b>0{i+1}</b>{t}</li>)}</ol></section>
<section className="section voices" id="voices"><div className="section-heading"><div><p className="eyebrow">VOICE / お客様の声</p><h2>嬉しいお声を<br/>いただいています。</h2></div><a href="#voices">もっと見る <ArrowRight/></a></div><div className="voice-grid">{[['長年の肩こりが楽になりました！','デスクワークでつらかった肩が、施術後は驚くほど軽くなりました。','30代 女性'],['姿勢が良くなり、仕事の集中力もアップ','猫背が改善されて、見た目も気持ちも明るくなりました。','40代 男性'],['産後の腰痛が改善しました','丁寧に相談していただき、安心して通えました。','30代 女性']].map(([t,d,n],i)=><article key={t}><div className="avatar">{i===1?'♂':'♀'}</div><div><h3>「{t}」</h3><p>{d}</p><small>{n}</small></div></article>)}</div></section>
<section className="section info"><div className="doctor" id="doctor"><p className="eyebrow">DIRECTOR / 院長紹介</p><h2>身体と心に、<br/>丁寧に向き合う。</h2><div className="doctor-card"><div className="portrait">山田<br/>院長</div><div><h3>山田 恒一</h3><p>一人でも多くの方が、心身ともに健康で笑顔の毎日を過ごせるよう、丁寧な施術を心がけています。</p><a href="#doctor">院長の想いを見る <ArrowRight/></a></div></div></div><div className="access" id="access"><p className="eyebrow">ACCESS / アクセス</p><h2>駅から徒歩3分。</h2><p><MapPin/>神奈川県海老名市中央1-2-3<br/>やすらぎビル2F</p><p><Clock/>平日 10:00〜20:00<br/>土日 9:00〜18:00</p><p><Phone/>046-000-0000</p><div className="map">やすらぎ整体院 <MapPin size={34} weight="fill"/></div></div><div className="faq" id="faq"><p className="eyebrow">FAQ / よくある質問</p><h2>よくある質問</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
<section className="bottom-cta"><img src="/assets/hero.png" alt="光の中でリラックスする女性"/><div><h2>軽やかな毎日を、<br/>ここから。</h2><Button onClick={()=>setBooking(true)}>今すぐ予約する</Button></div></section></main><footer><a className="brand" href="#home"><Leaf size={31} weight="thin"/><span>やすらぎ整体院<small>YASURAGI SEITAIIN</small></span></a><nav>{nav.map(([t,id])=><a key={id} href={'#'+id}>{t}</a>)}</nav><p>© 2024 やすらぎ整体院. All rights reserved.</p></footer>{booking&&<Booking onClose={()=>setBooking(false)}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
