import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Bicycle, CalendarBlank, Car, CaretLeft, CaretRight, Clock, Heart, List, MapPin, Stethoscope, Syringe, Train, UsersThree, X, FirstAidKit, Plus } from '@phosphor-icons/react';
import './clinic.css';

const medical = [
  {id:'internal',title:'一般内科',Icon:Stethoscope,copy:'風邪・発熱・腹痛など\nさまざまな症状に対応',detail:'体調について気になることを、まずはご相談いただく診療案内のサンプルです。実際の対応範囲・受診方法は、ご利用になる医療機関へご確認ください。'},
  {id:'lifestyle',title:'生活習慣病',Icon:Heart,copy:'高血圧・糖尿病・脂質異常症\nなどの継続的な管理',detail:'生活習慣病の診療をご紹介するための表示例です。検査や治療の内容は、実際のクリニックの診療方針に合わせて編集してください。'},
  {id:'digestive',title:'消化器内科',Icon:FirstAidKit,copy:'胃の不調・腹痛・便通異常\nなどの診療',detail:'消化器の診療内容をご紹介する表示例です。検査設備、予約の要否、対応できる症状などを実際の情報に書き換えてください。'},
  {id:'respiratory',title:'呼吸器内科',Icon:Stethoscope,copy:'せき・息切れ・喘息\nなどの診療',detail:'呼吸器の診療案内のサンプルです。このページでは症状の判定や医療相談は行いません。診療内容は実際の医療機関にご確認ください。'},
  {id:'vaccine',title:'予防接種・健康診断',Icon:Syringe,copy:'インフルエンザ・各種ワクチン\n企業健診・特定健診',detail:'予防接種・健康診断の案内例です。実施内容・対象者・費用・予約方法は、実際のクリニックの最新情報へ差し替えてください。'}
];
const facilities = [
  {id:'reception',title:'受付',copy:'明るく清潔な空間でお迎えします'},
  {id:'waiting',title:'待合室',copy:'ゆったりとお過ごしいただけます'},
  {id:'examination',title:'診察室',copy:'プライバシーに配慮した個室'},
  {id:'treatment',title:'処置室',copy:'各種検査・処置に対応'},
  {id:'equipment',title:'医療機器',copy:'診療を支える検査機器'}
];
const faqs = [
  ['初めてでも予約は必要ですか？','予約の要否はクリニックごとに異なります。このテンプレートのWEB予約は入力・確認だけのデモです。実際に使う際は、予約サービスや受付の案内を設定してください。'],
  ['発熱がある場合はどうすればいいですか？','受診方法は医療機関によって異なります。実際に受診するクリニックへ、事前に連絡してご確認ください。このページから医療相談や診察の受付はできません。'],
  ['健康診断は予約が必要ですか？','この欄には健康診断の予約方法を記載します。対応する健診の種類・持ち物・注意事項は、実際のクリニックの情報に変更してください。'],
  ['駐車場はありますか？','駐車場の案内はサンプルです。ご利用時は、専用駐車場の有無・台数・近隣駐車場の情報を設定してください。'],
  ['クレジットカードは使えますか？','お支払い方法は未設定です。実際に利用できる決済方法を、この欄に記載してください。'],
  ['子どもも診てもらえますか？','診療対象の年齢は、実際の医療機関にご確認ください。このテンプレートにある家族向けの紹介は表示例です。']
];
const navigation=[['ホーム','home'],['当院について','about'],['診療内容','medical'],['医師紹介','doctor'],['院内設備','facility'],['診療時間','schedule'],['アクセス','access'],['よくある質問','faq']];
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};

export function App(){
  const [menu,setMenu]=useState(false),[modal,setModal]=useState(null),[slide,setSlide]=useState(0),[review,setReview]=useState(false);
  const [booking,setBooking]=useState({service:'一般内科',date:'',time:'09:00',name:'',email:'',agreed:false});
  const dialog=useRef(null),trigger=useRef(null);
  useEffect(()=>{if(!modal)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.showModal();return()=>{document.body.style.overflow=before;};},[modal]);
  useEffect(()=>{if(review)dialog.current?.querySelector('h2')?.focus();},[review]);
  function open(value){if(!modal)trigger.current=document.activeElement;setMenu(false);setModal(value);}
  function close(){dialog.current?.close();setModal(null);setReview(false);trigger.current?.focus?.();}
  function reserve(service='一般内科'){setBooking(b=>({...b,service}));setReview(false);open({kind:'booking',title:'WEB診療予約の入力デモ'});}
  function update(e){const {name,value,checked,type}=e.target;setBooking(b=>({...b,[name]:type==='checkbox'?checked:value}));}
  const button=(label='WEBで診療予約をする',kind='primary',action=()=>reserve())=><button className={`button ${kind}`} onClick={action}>{label}{kind==='header'?<CalendarBlank aria-hidden="true"/>:<ArrowRight aria-hidden="true"/>}</button>;
  const logo=()=> <a className="brand" href="#home" aria-label="そら内科クリニック トップ"><img src="/assets/logo.png" alt="そら内科クリニック SORA CLINIC"/></a>;
  const detail=(title,text,image)=>open({kind:'detail',title,text,image});
  const orderedFacilities=facilities.map((_,i)=>facilities[(i+slide)%facilities.length]);
  return <div className="page">
    <a href="#main" className="skip">本文へ移動</a>
    <header className="site-header" id="home">{logo()}<nav id="site-navigation" className={menu?'navigation open':'navigation'} aria-label="メインナビゲーション">{navigation.map(([text,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{text}</a>)}</nav>{button('WEB予約','header')}<button className="menu-toggle" aria-controls="site-navigation" aria-expanded={menu} aria-label={menu?'メニューを閉じる':'メニューを開く'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></header>
    <main id="main">
      <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src="/assets/hero.png" alt="笑顔で話を聞く女性医師のイメージ" fetchPriority="high"/><div className="hero-content"><h1 id="hero-title">ずっと、<br/>この街の健康を<br/>ともに。</h1><p className="hero-description">気になること、いつでも気軽に相談できる<br/>あなたのかかりつけ医でありたい。</p><div className="hero-benefits">{[[Stethoscope,'内科・生活習慣病\n幅広く対応'],[UsersThree,'子どもから大人まで\n家族で通える'],[Clock,'土曜診療\n平日夜も安心']].map(([Icon,text])=><div key={text}><span><Icon/></span><p>{text}</p></div>)}</div>{button()}<small className="hero-note">初めての方も、高齢の方もご相談いただけます</small></div><p className="hero-script">健康な<br/>毎日が、<br/>いちばんの幸せ。</p><div className="station-badge"><small>海老名駅から</small><span>徒歩<strong>3</strong>分</span><small>土曜も診療</small></div></section>
      <div className="news-strip"><span>お知らせ</span><time dateTime="2024-10-01">2024.10.01</time><button onClick={()=>open({kind:'news',title:'お知らせ'})}>インフルエンザワクチンの予約を開始しました</button><button className="news-all" onClick={()=>open({kind:'news',title:'お知らせ一覧'})}>一覧を見る<ArrowRight/></button></div>
      <section className="benefits" aria-labelledby="benefits-title"><h2 id="benefits-title">そら内科クリニックの <em>4</em>つの特徴</h2><div className="benefit-grid">{[[Heart,'丁寧でわかりやすい診療','一人ひとりに寄り添います'],[UsersThree,'家族みんなの','かかりつけ医'],[CalendarBlank,'平日夜・土曜も診療','忙しい方も通いやすい'],[Train,'駅近で通いやすい','海老名駅 徒歩3分']].map(([Icon,title,copy])=><div key={title}><Icon aria-hidden="true"/><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
      <section className="about" id="about"><div className="about-copy"><p className="eyebrow">ABOUT</p><h2>地域の皆さまの<br/>健康な毎日を支えるクリニック</h2><p>そら内科クリニックは、内科・生活習慣病を中心に、<br className="desktop-break"/>子どもからご高齢の方まで、幅広い世代の<br className="desktop-break"/>健康をサポートする地域密着のクリニックです。<br/>病気の治療だけでなく、予防や健康相談も大切にし、<br className="desktop-break"/>皆さまの「安心できる場所」でありたいと考えています。</p>{button('当院について詳しく見る','outline',()=>detail('当院について','地域の皆さまと、長くお付き合いできるクリニックを目指して。こちらは紹介文のサンプルです。実際の診療方針、沿革、施設の情報に変更してご利用ください。','facade'))}</div><div className="about-photo"><img src="/assets/facade.png" alt="緑に囲まれたクリニック外観のイメージ" loading="lazy"/><p><span>この街で、</span><span>ずっと。</span><span>皆さまとともに。</span></p></div></section>
      <section className="medical section" id="medical"><div className="section-heading"><p className="eyebrow">MEDICAL</p><h2>診療内容</h2><p>幅広い症状・お悩みに対応しています。気になることがあればお気軽にご相談ください。</p></div><div className="medical-grid">{medical.map(item=><button key={item.id} className="medical-card" onClick={()=>open({kind:'medical',title:item.title,item})}><img src={`/assets/${item.id}.png`} alt={`${item.title}の診療イメージ`} loading="lazy"/><div><h3><item.Icon aria-hidden="true"/>{item.title}</h3><p>{item.copy}</p><ArrowRight className="card-arrow" aria-hidden="true"/></div></button>)}</div>{button('診療内容をもっと見る','outline',()=>open({kind:'medical-all',title:'診療内容のご案内'}))}</section>
      <section className="doctor" id="doctor"><div className="doctor-photo-frame"><img className="doctor-photo" src="/assets/doctor.png" alt="院長紹介用の医師イメージ写真" loading="lazy"/></div><div className="doctor-copy"><p className="eyebrow">DOCTOR</p><h2>医師紹介</h2><p>地域の皆さまの健康を、<br/>長く支えるパートナーとして。</p><h3><span>院長</span> 佐藤 健一</h3><small>医師名・経歴は紹介用のサンプルです。<br/>実際の情報に変更してご利用ください。</small>{button('医師紹介を見る','outline',()=>detail('院長からのごあいさつ','地域の皆さまに気軽にご相談いただける場所を目指して。一人ひとりのお話を大切に、わかりやすいご案内を心がけています。医師名・写真・経歴は架空のサンプルです。ご利用時は、実際の医師紹介へ差し替えてください。','doctor'))}</div><blockquote><h3>「気軽に相談できる<br/>クリニックでありたい」</h3><p>どんな小さな症状でも、<br/>お気軽にご相談ください。<br/>皆さまの健康と安心のために、<br/>丁寧でわかりやすい診療を<br/>心がけています。</p></blockquote></section>
      <section className="facility section" id="facility"><div className="section-heading"><p className="eyebrow">FACILITY</p><h2>院内のご紹介</h2></div><div className="facility-carousel"><button className="carousel-control prev" aria-label="前の院内写真へ" onClick={()=>setSlide((slide+4)%5)}><CaretLeft/></button><div className="facility-grid">{orderedFacilities.map(item=><button key={item.id} onClick={()=>detail(item.title,`${item.copy}。写真・設備はサンプルです。実際の施設設備に合わせてご案内を変更してください。`,item.id)}><img src={`/assets/${item.id}.png`} alt={`${item.title}のイメージ`} loading="lazy"/><h3>{item.title}</h3><p>{item.copy}</p></button>)}</div><button className="carousel-control next" aria-label="次の院内写真へ" onClick={()=>setSlide((slide+1)%5)}><CaretRight/></button></div><p className="sr-only" role="status">院内写真の先頭：{orderedFacilities[0].title}</p>{button('院内の詳細を見る','outline',()=>open({kind:'facilities',title:'院内設備のご案内'}))}</section>
      <section className="information section"><div className="schedule" id="schedule"><p className="eyebrow">SCHEDULE</p><h2>診療時間</h2><table><caption className="sr-only">診療時間の表示例</caption><thead><tr>{['診療時間','月','火','水','木','金','土','日・祝'].map(day=><th scope="col" key={day}>{day}</th>)}</tr></thead><tbody><tr><th scope="row">9:00 - 12:30</th>{[true,true,true,true,true,true,false].map((open,i)=><td key={i} aria-label={open?'診療':'休診'}>{open?'●':'−'}</td>)}</tr><tr><th scope="row">15:00 - 18:30</th>{[true,true,false,false,true,false,false].map((open,i)=><td key={i} aria-label={open?'診療':'休診'}>{open?'●':'−'}</td>)}</tr></tbody></table><p>休診日：日曜・祝日・水曜午後・木曜午後・土曜午後<br/>※受付は診療終了の30分前までです。</p></div><div className="access" id="access"><div><p className="eyebrow">ACCESS</p><h2>アクセス</h2><p><MapPin/>神奈川県海老名市中央1-2-3<br/>そらビル1F</p><p><Train/>小田急線・相鉄線・JR相模線<br/>「海老名駅」徒歩3分</p><p><Car/>近隣にコインパーキングあり</p><p><Bicycle/>駐輪場あり</p>{button('Googleマップを見る','outline',()=>open({kind:'access',title:'アクセス情報の設定について'}))}</div><button className="map-button" aria-label="アクセス地図の説明を見る" onClick={()=>open({kind:'access',title:'アクセス情報の設定について'})}><img src="/assets/map.png" alt="そら内科クリニックの架空のアクセス地図" loading="lazy"/></button></div></section>
      <section className="faq section" id="faq"><p className="eyebrow">FAQ</p><h2>よくある質問</h2><div className="faq-grid">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true"><Plus/></span></summary><p>{a}</p></details>)}</div></section>
      <section className="bottom-cta"><img src="/assets/family.png" alt="緑の中で過ごす家族のイメージ" loading="lazy"/><h2>健やかな未来を、<br/>この街でともに。</h2><div>{button()}<p>24時間いつでもご予約いただけます</p></div></section>
    </main>
    <footer className="site-footer">{logo()}<nav aria-label="フッターナビゲーション">{navigation.map(([text,id])=><a key={id} href={`#${id}`}>{text}</a>)}</nav><div><button onClick={()=>open({kind:'privacy',title:'個人情報の取り扱い'})}>プライバシーポリシー</button><span>・</span><a href="#home">サイトトップ</a><p>© 2024 SORA CLINIC. All rights reserved.</p></div></footer><p className="demo-disclaimer">架空のクリニックのLPテンプレートです。写真・医師情報・住所・診療時間はサンプルです。医療相談・予約送信・決済は行いません。</p>
    {modal&&<dialog className="modal" ref={dialog} aria-labelledby="dialog-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="modal-body"><button className="modal-close" onClick={close} aria-label="閉じる"><X/></button><p className="eyebrow">SORA CLINIC / TEMPLATE DEMO</p><h2 id="dialog-title" tabIndex={-1}>{review?'入力内容の確認':modal.title}</h2>
      {modal.kind==='booking'&&<><p className="notice">入力・確認だけのデモです。送信・保存・診療予約・空き枠の確保は行いません。実際の症状や医療情報は入力しないでください。</p>{review?<div className="booking-review"><p role="status">入力内容をご確認ください。<strong>予約は確定していません。</strong></p><dl>{[['診療メニュー',booking.service],['希望日時',`${booking.date} ${booking.time}`],['お名前',booking.name],['メールアドレス',booking.email]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{button('入力内容を修正する','outline full',()=>setReview(false))}{button('確認を終える','primary full',close)}</div>:<form onSubmit={e=>{e.preventDefault();setReview(true);}}><label>診療メニュー<select name="service" value={booking.service} onChange={update}>{medical.map(m=><option key={m.id}>{m.title}</option>)}</select></label><div className="form-grid"><label>希望日 <em>必須</em><input type="date" name="date" min={localDate()} required value={booking.date} onChange={update}/></label><label>希望時間<select name="time" value={booking.time} onChange={update}>{['09:00','10:00','11:00','15:00','16:00','17:00'].map(t=><option key={t}>{t}</option>)}</select></label></div><p className="form-help">曜日・時間の空き状況は確認していません。</p><label>お名前 <em>必須</em><input name="name" value={booking.name} onChange={update} required maxLength={80} autoComplete="name"/></label><label>メールアドレス <em>必須</em><input name="email" type="email" value={booking.email} onChange={update} required maxLength={254} autoComplete="email"/></label><label className="consent"><input name="agreed" type="checkbox" checked={booking.agreed} onChange={update} required/>予約が送信されないデモであることを確認しました。</label><button type="submit" className="button primary full">入力内容を確認する<ArrowRight/></button></form>}</>}
      {modal.kind==='detail'&&<><img className="detail-image" src={`/assets/${modal.image}.png`} alt={modal.title}/><p className="detail-copy">{modal.text}</p><p className="notice">写真・紹介文は、LPテンプレートの表示例です。</p></>}
      {modal.kind==='medical'&&<><img className="detail-image" src={`/assets/${modal.item.id}.png`} alt={modal.item.title}/><p className="detail-copy">{modal.item.detail}</p>{button('この診療メニューで予約入力へ','primary full',()=>reserve(modal.item.title))}</>}
      {modal.kind==='medical-all'&&<><p className="notice">下記は診療案内の表示例です。実際の診療を行う施設ではありません。</p><div className="detail-list">{medical.map(m=><button key={m.id} onClick={()=>open({kind:'medical',title:m.title,item:m})}><img src={`/assets/${m.id}.png`} alt=""/><span>{m.title}</span><ArrowRight/></button>)}</div></>}
      {modal.kind==='facilities'&&<div className="detail-list">{facilities.map(f=><button key={f.id} onClick={()=>detail(f.title,`${f.copy}。設備はサンプルです。`,f.id)}><img src={`/assets/${f.id}.png`} alt=""/><span>{f.title}</span><ArrowRight/></button>)}</div>}
      {modal.kind==='news'&&<><p className="notice">以下はサンプルのお知らせです。実際の受付情報ではありません。</p><article className="news-detail"><time>2024.10.01</time><h3>インフルエンザワクチンの予約を開始しました</h3><p>接種の案内文を掲載するための表示例です。受付期間・料金・予約方法は実際の情報へ変更してください。</p></article><article className="news-detail"><time>2024.09.01</time><h3>ホームページを公開しました</h3><p>診療案内・院内の設備・アクセス情報をご紹介しています。</p></article></>}
      {modal.kind==='access'&&<><img className="detail-map" src="/assets/map.png" alt="架空の所在地の地図"/><p className="detail-copy">住所・地図・駅からの所要時間はサンプルです。誤った場所へ案内しないよう、このデモでは外部地図へ移動しません。実際に使う際は、住所と地図画像を変更し、GoogleマップのURLを設定してください。</p></>}
      {modal.kind==='privacy'&&<p className="detail-copy">このデモでは、入力した情報をサーバーに送信したり、ブラウザーへ永続保存したりしません。ページを再読み込みすると入力内容は消えます。実際に予約フォームを接続する際は、運営者の個人情報の取り扱い方針に書き換えてください。</p>}
    </div></dialog>}
  </div>;
}
