const $=(s)=>document.querySelector(s);
const booking=$('#booking-dialog'),info=$('#info-dialog'),form=$('#booking-form');
const programs={strength:['筋力トレーニング','マシンやフリーウェイトを使って、全身をバランスよく鍛えます。基本のフォームから丁寧にご案内するので、初めての方も自分のペースで取り組めます。'],cardio:['有酸素トレーニング','ランニングマシンやバイクを使って、持久力アップを目指します。体力やその日のコンディションに合わせて強度を調整できます。'],yoga:['ヨガ・ピラティス','呼吸と姿勢を意識しながら、しなやかなカラダづくりを。柔軟性や体幹を整え、日々のリフレッシュにもつながるプログラムです。'],personal:['パーソナルトレーニング','あなたの目標や運動経験に合わせたマンツーマン指導。フォームや負荷を確認しながら、一緒にトレーニングを進めます。'],group:['グループレッスン','仲間と一緒に、楽しくカラダを動かす時間。インストラクターのリードで、無理なく運動習慣をつくります。']};
function openDialog(dialog){dialog.showModal();document.body.classList.add('modal-open')}
function closeDialog(dialog){dialog.close();document.body.classList.remove('modal-open')}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.close-dialog').addEventListener('click',()=>closeDialog(dialog));dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog)}})});
function book(plan,program){if(info.open)info.close();$('#booking-review').hidden=true;form.hidden=false;if(plan)form.elements.plan.value=plan;if(program)form.elements.program.value=program;openDialog(booking)}
document.querySelectorAll('[data-book]').forEach(button=>button.addEventListener('click',()=>book(button.dataset.plan)));
const now=new Date();const localDate=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;form.elements.date.min=localDate;
form.addEventListener('submit',e=>{e.preventDefault();const list=$('#review-list');list.replaceChildren();const labels={name:'お名前',email:'メールアドレス',date:'ご希望日',time:'ご希望時間',plan:'気になるプラン',program:'体験したいプログラム'};for(const [name,value] of new FormData(form)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=labels[name];dd.textContent=value;list.append(dt,dd)}form.hidden=true;$('#booking-review').hidden=false;booking.scrollTop=0;$('#edit-booking').focus()});
$('#edit-booking').addEventListener('click',()=>{$('#booking-review').hidden=true;form.hidden=false;form.elements.name.focus()});
$('#finish-demo').addEventListener('click',()=>{closeDialog(booking);form.reset();$('#booking-review').hidden=true;form.hidden=false});
function showInfo(title,render){$('#info-title').textContent=title;const content=$('#info-content');content.replaceChildren();render(content);openDialog(info)}
function paragraph(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p)}
function programContent(parent,key){const [title,description]=programs[key];const image=document.createElement('img');image.src=`assets/${key}.webp`;image.alt=title;parent.append(image);paragraph(parent,description);const button=document.createElement('button');button.className='button full';button.textContent='このプログラムを体験する →';button.onclick=()=>book(null,title);parent.append(button)}
document.querySelectorAll('[data-program]').forEach(button=>button.addEventListener('click',()=>showInfo(programs[button.dataset.program][0],parent=>programContent(parent,button.dataset.program))));
$('#show-programs').addEventListener('click',()=>showInfo('プログラム一覧',parent=>{for(const [key,[title,description]] of Object.entries(programs)){const article=document.createElement('article'),h=document.createElement('h3');h.textContent=title;article.append(h);paragraph(article,description);const button=document.createElement('button');button.className='outline';button.textContent='このプログラムを体験する →';button.onclick=()=>book(null,title);article.append(button);parent.append(article)}}));
$('#show-trainers').addEventListener('click',()=>showInfo('目標に寄り添うトレーナー',parent=>{document.querySelectorAll('.trainers article').forEach(card=>{const article=document.createElement('article');const heading=document.createElement('h3');heading.textContent=card.querySelector('h3').textContent;article.append(heading);paragraph(article,card.querySelector('p').textContent);parent.append(article)});paragraph(parent,'運動経験や体力、お悩みをお聞かせください。無料体験では、あなたに合ったトレーニングをご相談いただけます。');const b=document.createElement('button');b.className='button full';b.textContent='無料体験で相談する →';b.onclick=()=>book();parent.append(b)}));
$('#store-info').addEventListener('click',()=>showInfo('MOVE FIT 渋谷店',parent=>{paragraph(parent,'東京都渋谷区神南1-1-1');paragraph(parent,'営業時間：平日 7:00–23:00 ／ 土日祝 8:00–20:00');paragraph(parent,'JR渋谷駅 徒歩5分。東京メトロ渋谷駅 徒歩3分。近隣にコインパーキングがあります。');paragraph(parent,'この店舗情報はデザイン見本用のサンプルです。実在する店舗の案内ではありません。')}));
document.querySelectorAll('[data-info]').forEach(b=>b.addEventListener('click',()=>showInfo(b.dataset.info==='legal'?'特定商取引法に基づく表記':'プライバシーポリシー',parent=>{paragraph(parent,b.dataset.info==='legal'?'このサイトはフィットネスジムのLPデザイン見本です。商品・サービスの販売や契約、決済は行っていません。':'このデモサイトでは、予約フォームに入力した情報をサーバーへ送信・保存しません。入力内容は画面上の確認表示にのみ使用します。');paragraph(parent,'掲載されている店舗・スタッフ・料金・体験談はサンプルです。')})));
const menu=$('.menu-toggle'),nav=$('#navigation');menu.addEventListener('click',()=>{const isOpen=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(isOpen));menu.setAttribute('aria-label',isOpen?'メニューを閉じる':'メニューを開く');menu.textContent=isOpen?'CLOSE':'MENU';nav.classList.toggle('open',isOpen)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','メニューを開く');menu.textContent='MENU'}));
document.querySelectorAll('[data-icon]').forEach(el=>{const img=document.createElement('img');img.src=`assets/icon-${el.dataset.icon}.webp`;img.alt='';img.width=48;img.height=48;el.append(img)});
