import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Bathtub, Bed, CalendarBlank, Car, CaretRight, ForkKnife, List, Mountains, Train, AirplaneTilt, X } from '@phosphor-icons/react';
import './ryokan.css';

const features = [
  {id:'rooms',title:'客室',en:'ROOMS',image:'rooms',copy:'窓の外に広がる四季の景色。\n心ほどける和の空間。',link:'客室を見る',detail:'畳の香りと木の温もりに包まれる和室。窓辺で移りゆく山の景色を眺めながら、ゆっくりとお過ごしください。',facts:[['客室例','和室10畳・広縁付き'],['設備例','バス・トイレ、冷暖房、Wi-Fi'],['ご案内','客室設備・定員はサンプルです。']]},
  {id:'cuisine',title:'お料理',en:'CUISINE',image:'cuisine',copy:'旬の恵みを、\n一皿一皿に込めて。',link:'お料理を見る',detail:'季節の食材を少しずつ、丁寧に。彩りも香りも楽しめる会席料理で、旅の夜をお迎えします。',facts:[['お食事例','季節の会席料理・和朝食'],['お食事処','落ち着いた和のダイニング'],['ご案内','献立は一例です。アレルギー対応は実際の施設へご確認ください。']]},
  {id:'onsen',title:'温泉',en:'ONSEN',image:'onsen',copy:'自然に包まれた湯で、\n心も体もリフレッシュ。',link:'温泉を見る',detail:'木々のざわめきと、湯の流れる音。開放的な露天風呂で、日々の忙しさから少し離れる時間を。',facts:[['お風呂例','露天風呂・内湯'],['景色','四季の山並みと庭園'],['ご案内','源泉・泉質・営業時間等は未設定です。効能を保証するものではありません。']]},
  {id:'facilities',title:'館内案内',en:'FACILITIES',image:'lounge',copy:'寛ぎのひとときを彩る\n充実の施設。',link:'館内案内を見る',detail:'景色を楽しむラウンジ、木の温もりが伝わる廊下。思い思いの場所で、心地よいひとときをお過ごしください。',facts:[['施設例','ラウンジ・お食事処・売店'],['ご到着・ご出発の例','チェックイン15:00 / アウト11:00'],['ご案内','設備・営業時間は実際の施設情報へ変更してください。']]},
];
const plans = [
  {id:'spring',tag:'春限定',title:'桜を楽しむ特別会席プラン',copy:'春の宵とともに、桜の絶景を。',period:'3月〜4月',price:18700,image:'spring',season:'春'},
  {id:'standard',tag:'スタンダード',title:'月の湯 基本会席プラン',copy:'四季の恵みを味わう、\n当館一番人気のプラン。',period:'通年',price:16500,image:'standard',season:'通年'},
  {id:'autumn',tag:'秋限定',title:'紅葉を楽しむ特別会席プラン',copy:'色づく山々と旬の味覚を堪能。',period:'10月〜11月',price:19800,image:'autumn',season:'秋'},
];
const sights = [
  {id:'shrine',title:'○○神社',time:'車で15分',detail:'木々に囲まれた社殿を、静かに散策。旅先での小さな発見をお楽しみください。'},
  {id:'waterfall',title:'○○渓谷',time:'車で20分',detail:'緑の渓谷と流れる水の音を楽しむ散策コース。所要時間・経路は実際の場所に合わせて設定してください。'},
  {id:'town',title:'○○温泉街',time:'車で25分',detail:'夕暮れには灯りがともる温泉街。まち歩きを楽しむ旅のひとこまに。'},
  {id:'lake',title:'○○湖畔',time:'車で30分',detail:'山々を映す水辺で、ゆったりと深呼吸。観光スポット名は仮の表示です。'},
];
const nav=[['ホーム','home'],['客室','rooms'],['お料理','cuisine'],['温泉','onsen'],['料金プラン','plans'],['館内案内','facilities'],['周辺観光','sightseeing'],['交通アクセス','access']];
const yen=n=>n.toLocaleString('ja-JP');
const dateString=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>dateString(new Date());
const nextDay=value=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+1);return dateString(d);};

export function App(){
  const [menu,setMenu]=useState(false),[modal,setModal]=useState(null),[season,setSeason]=useState('すべて'),[review,setReview]=useState(false);
  const [booking,setBooking]=useState({plan:'standard',checkin:'',checkout:'',adults:'2',rooms:'1',name:'',email:'',message:'',agreed:false});
  const dialog=useRef(null);
  useEffect(()=>{if(!modal)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.showModal();return()=>{document.body.style.overflow=before;};},[modal]);
  function close(){dialog.current?.close();setModal(null);setReview(false);}
  function reserve(id='standard'){setBooking(b=>({...b,plan:id}));setReview(false);setMenu(false);setModal({kind:'booking'});}
  function update(e){const {name,value,type,checked}=e.target;setBooking(b=>{const n={...b,[name]:type==='checkbox'?checked:value};if(name==='checkin'&&value&&(!b.checkout||b.checkout<=value))n.checkout=nextDay(value);return n;});}
  const selectedPlan=plans.find(p=>p.id===booking.plan);
  const cta=(label='宿泊予約',extra='')=><button className={`reservation-button ${extra}`} onClick={()=>reserve()}><CalendarBlank weight="fill" aria-hidden="true"/>{label}{label!=='宿泊予約'&&<ArrowRight aria-hidden="true"/>}</button>;
  const logo=()=> <a className="logo" href="#home" aria-label="やすらぎの宿 月の湯 トップ"><img src="/assets/logo.png" alt="やすらぎの宿 月の湯 TSUKI NO YU"/></a>;
  const title=modal?.kind==='booking'?(review?'ご希望内容の確認':'宿泊予約の入力デモ'):modal?.kind==='plans'?'宿泊プラン一覧':modal?.kind==='access'?'交通アクセスのご案内':modal?.kind==='sights'?'周辺観光のご案内':modal?.item?.title;
  return <>
    <a className="skip-link" href="#main">本文へ移動</a>
    <section className="hero" id="home" aria-labelledby="hero-title"><img className="hero-image" src="/assets/hero.png" alt="夕暮れの山々を望む、灯りのともる露天風呂" fetchPriority="high"/>
      <header className="site-header">{logo()}<nav id="main-navigation" className={menu?'navigation open':'navigation'} aria-label="メインナビゲーション">{nav.map(([label,id])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}</nav>{cta()}<button className="menu-toggle" aria-expanded={menu} aria-controls="main-navigation" aria-label={menu?'メニューを閉じる':'メニューを開く'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></header>
      <div className="hero-copy"><h1 id="hero-title">旅の先に、<br/>もうひとつのふるさとがある。</h1><p>四季が彩る、やすらぎのひとときを。</p></div><p className="vertical-copy">こころ、ほどける。</p>
    </section>
    <main id="main">
      <section className="benefits paper" aria-label="月の湯の魅力">{[[Bathtub,'源泉かけ流しの温泉','大自然に包まれた\n癒しの湯'],[ForkKnife,'季節を味わう会席料理','地元の旬の食材を\n丁寧に仕立てて'],[Bed,'くつろぎの客室','和の趣と快適さを\n兼ね備えた空間'],[Mountains,'四季折々の美しい景色','訪れるたびに違う\n特別な出会い']].map(([Icon,heading,copy])=><div key={heading}><Icon weight={Icon===Bed?'fill':'regular'} aria-hidden="true"/><h2>{heading}</h2><p>{copy}</p></div>)}</section>
      <section className="feature-grid paper" aria-label="宿のご案内">{features.map(item=><article className="feature" id={item.id} key={item.id}><button className="feature-image" onClick={()=>setModal({kind:'feature',item})} aria-label={`${item.title}の詳細を見る`}><img src={`/assets/${item.image}.png`} alt={`${item.title}のサンプル写真`} loading="lazy"/><span className="feature-title"><strong>{item.title}</strong><small>{item.en}</small></span></button><div className="feature-copy"><p>{item.copy}</p><button className="text-link" onClick={()=>setModal({kind:'feature',item})}>{item.link}<ArrowRight aria-hidden="true"/></button></div></article>)}</section>
      <section className="plans-section" id="plans" aria-labelledby="plans-heading"><img className="plans-background" src="/assets/onsen.png" alt="" loading="lazy"/><div className="plans-inner"><header className="section-heading"><h2 id="plans-heading">宿泊プラン<span>PLAN</span></h2><button className="outline light" onClick={()=>{setSeason('すべて');setModal({kind:'plans'});}}>すべてのプランを見る<ArrowRight aria-hidden="true"/></button></header><div className="plan-grid">{plans.map(plan=><button className="plan-card" key={plan.id} onClick={()=>reserve(plan.id)} aria-label={`${plan.title}を選ぶ`}><img src={`/assets/${plan.image}.png`} alt={`${plan.season}の宿泊イメージ`} loading="lazy"/><div className="plan-copy"><h3>【{plan.tag}】<br/>{plan.title}</h3><p>{plan.copy}{plan.period!=='通年'&&<><br/>期間：{plan.period}</>}</p><div className="plan-price"><span>お一人様</span><strong>{yen(plan.price)}</strong>円〜<small>（税込）</small><CaretRight aria-hidden="true"/></div></div></button>)}</div></div></section>
      <section className="local-information" aria-label="アクセスと観光"><div className="access" id="access"><div className="access-copy"><h2>交通アクセス<span>ACCESS</span></h2><div className="travel"><Train weight="fill"/><p><strong>電車でお越しの場合</strong><br/>最寄り駅「○○駅」より、<br/>送迎バスで約15分</p></div><div className="travel"><Car/><p><strong>お車でお越しの場合</strong><br/>○○自動車道「○○IC」より<br/>約20分</p></div><div className="travel"><AirplaneTilt weight="fill"/><p><strong>飛行機でお越しの場合</strong><br/>○○空港より、車で約60分</p></div><button className="outline" onClick={()=>setModal({kind:'access'})}>詳しいアクセス情報を見る<ArrowRight aria-hidden="true"/></button></div><button className="map-button" onClick={()=>setModal({kind:'access'})} aria-label="アクセス図の説明を見る"><img src="/assets/map.png" alt="月の湯へのアクセス図のサンプル。実在する所在地ではありません。" loading="lazy"/></button></div><div className="sightseeing" id="sightseeing"><h2>周辺観光<span>SIGHTSEEING</span></h2><div className="sight-grid">{sights.map(s=><button className="sight" key={s.id} onClick={()=>setModal({kind:'sight',item:s})}><img src={`/assets/${s.id}.png`} alt={`${s.title}の観光イメージ`} loading="lazy"/><span>{s.title}</span><small>（{s.time}）</small></button>)}</div><button className="outline" onClick={()=>setModal({kind:'sights'})}>周辺観光を見る<ArrowRight aria-hidden="true"/></button></div></section>
    </main>
    <footer className="site-footer"><img className="footer-image" src="/assets/footer.png" alt="" loading="lazy"/>{logo()}<div className="footer-copy"><h2>また、帰ってきたくなる場所。</h2><p>日常を離れ、特別な時間をお過ごしください。</p></div>{cta('宿泊予約はこちら')}</footer><div className="demo-note">架空の旅館のテンプレートです。写真・料金・温泉情報・所在地はサンプルです。予約・決済は行われません。</div>
    {modal&&<dialog ref={dialog} className="modal" aria-labelledby="modal-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="modal-content"><button className="modal-close" aria-label="閉じる" onClick={close}><X/></button><p className="modal-kicker">TSUKI NO YU / DEMO</p><h2 id="modal-title">{title}</h2>
      {modal.kind==='booking'&&<><p className="notice">入力・確認だけのデモです。空室照会・送信・保存・予約確定・決済は行いません。</p>{!review?<form onSubmit={e=>{e.preventDefault();setReview(true);}}><label>宿泊プラン<select name="plan" value={booking.plan} onChange={update}>{plans.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><div className="form-grid"><label>チェックイン <em>必須</em><input type="date" name="checkin" min={today()} value={booking.checkin} onChange={update} required/></label><label>チェックアウト <em>必須</em><input type="date" name="checkout" min={booking.checkin?nextDay(booking.checkin):nextDay(today())} value={booking.checkout} onChange={update} required/></label><label>大人<select name="adults" value={booking.adults} onChange={update}>{[1,2,3,4,5,6].map(n=><option value={n} key={n}>{n}名</option>)}</select></label><label>客室数<select name="rooms" value={booking.rooms} onChange={update}>{[1,2,3].map(n=><option value={n} key={n}>{n}室</option>)}</select></label></div><label>お名前 <em>必須</em><input name="name" value={booking.name} onChange={update} required maxLength={80} autoComplete="name"/></label><label>メールアドレス <em>必須</em><input name="email" type="email" value={booking.email} onChange={update} required maxLength={254} autoComplete="email"/></label><label>ご相談・ご要望<textarea name="message" value={booking.message} onChange={update} rows={3} maxLength={1000}/></label><label className="checkbox"><input name="agreed" type="checkbox" checked={booking.agreed} onChange={update} required/>予約が送信されないデモであることを確認しました。</label><button className="reservation-button full" type="submit">入力内容を確認する<ArrowRight/></button></form>:<div className="review"><p className="review-status" role="status">入力内容をご確認ください。<br/><strong>予約はまだ送信されていません。</strong></p><dl>{[['プラン',selectedPlan.title],['ご宿泊日',`${booking.checkin} 〜 ${booking.checkout}`],['人数・客室',`大人${booking.adults}名 / ${booking.rooms}室`],['お名前',booking.name],['メールアドレス',booking.email],['ご相談・ご要望',booking.message||'未記入']].map(([dt,dd])=><div key={dt}><dt>{dt}</dt><dd>{dd}</dd></div>)}</dl><p className="notice">表示料金は参考価格です。宿泊日・人数による料金計算や空室の確保は行っていません。</p><button className="outline full" onClick={()=>setReview(false)}>入力内容を修正する</button><button className="reservation-button full" onClick={close}>確認を終える</button></div>}</>}
      {modal.kind==='feature'&&<><img className="modal-photo" src={`/assets/${modal.item.image}.png`} alt={modal.item.title}/><p className="detail-text">{modal.item.detail}</p><dl className="facts">{modal.item.facts.map(([dt,dd])=><div key={dt}><dt>{dt}</dt><dd>{dd}</dd></div>)}</dl>{cta('宿泊予約はこちら','full')}</>}
      {modal.kind==='plans'&&<><p className="notice">プラン・価格は表示例です。実際の販売は行っていません。</p><div className="filters" role="group" aria-label="季節で絞り込む">{['すべて','通年','春','秋'].map(s=><button key={s} aria-pressed={season===s} onClick={()=>setSeason(s)}>{s}</button>)}</div><div className="modal-plans">{plans.filter(p=>season==='すべて'||p.season===season).map(p=><button key={p.id} className="modal-plan" onClick={()=>reserve(p.id)}><img src={`/assets/${p.image}.png`} alt=""/><span><strong>{p.title}</strong><small>期間：{p.period} / 1泊2食付き（表示例）</small><span>{yen(p.price)}円〜（税込）</span></span><ArrowRight/></button>)}</div></>}
      {modal.kind==='access'&&<><img className="modal-map" src="/assets/map.png" alt="所在地未設定のアクセス図サンプル"/><p className="detail-text">地図・駅名・所要時間は、テンプレート用のサンプルです。実在する旅館の所在地や送迎サービスを示すものではありません。</p><p className="notice">ご利用時は、住所・駐車場・送迎の条件を書き換えてください。地図サービスへのリンクも編集ガイドの手順で設定できます。</p></>}
      {modal.kind==='sight'&&<><img className="modal-photo" src={`/assets/${modal.item.id}.png`} alt={modal.item.title}/><p className="detail-text">{modal.item.detail}</p><p className="notice">スポット名・写真・移動時間はすべてサンプルです。</p></>}
      {modal.kind==='sights'&&<><p className="notice">掲載スポットは表示例です。実際の観光情報へ差し替えてご利用ください。</p><div className="modal-sights">{sights.map(s=><button key={s.id} onClick={()=>setModal({kind:'sight',item:s})}><img src={`/assets/${s.id}.png`} alt=""/><span>{s.title}<small>（{s.time}）</small></span><ArrowRight/></button>)}</div></>}
    </div></dialog>}
  </>;
}
